spring:
  data:
    redis:
      database: 0
      host: localhost
      port: 6379

  application:
    name: knowledge-base
  datasource:
    url: jdbc:mysql://localhost:3306/knowledge_base?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080

jwt:
  secret: knowledge-base-secret-key-must-be-at-least-32-bytes

tencent:
  cos:
    secret-id: AKID5GEzHOJ0UmsmgV9dw65572nOo491iDbo
    secret-key: 3tb6OTL0UlRvDJE11ucFjDqHVYRP9i6H
    region: ap-chengdu
    bucket: keep-noteuserinfo-1409092538
